//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licenses.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicenseKey
    {
        public long LicenseKeyId { get; set; }
        public string LicenseKey1 { get; set; }
        public bool IsActivated { get; set; }
        public bool IsAssigned { get; set; }
        public Nullable<System.DateTime> AssignedOn { get; set; }
        public Nullable<System.DateTime> ActivatedOn { get; set; }
        public Nullable<long> LicenseUserId { get; set; }
        public int LicenseTypeId { get; set; }
        public string ActivatedBy { get; set; }
    
        public virtual LicenseType LicenseType { get; set; }
        public virtual LicenseUser LicenseUser { get; set; }
    }
}
